/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bascula;

import bascula.DAO.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author JoaquinArmando
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Principal() {
        initComponents();
        this.setLocationCenter();
        if ((!jtfHoraEntrada.getText().equals("") && !jtfHoraEntrada.getText().equals(" "))
                && (!jtfPesoEntrada.getText().equals("") && !jtfPesoEntrada.getText().equals(" "))) {
            jbLeerEntrada.setEnabled(false);
        } else {
            jbLeerEntrada.setEnabled(true);
        }
        jtfIdPesada.setEditable(false);
        jtfHoraEntrada.setEditable(false);
//        jtfPesoEntrada.setEditable(false);
        jtfHoraSalida.setEditable(false);
//        jtfPesoSalida.setEditable(false);
        jbLeerSalida.setEnabled(false);
        jbImprimir.setEnabled(true);

        ArrayList<Usuario> usuarios = new UsuarioDAO().consultar();
        for (Usuario usuario : usuarios) {
            jcbUsuarios.addItem(usuario.getUsuario());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoPesada = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfIdPesada = new javax.swing.JTextField();
        jtfPlacas = new javax.swing.JTextField();
        jtfOperador = new javax.swing.JTextField();
        jtfHoraEntrada = new javax.swing.JTextField();
        jtfPesoEntrada = new javax.swing.JTextField();
        jtfHoraSalida = new javax.swing.JTextField();
        jtfPesoSalida = new javax.swing.JTextField();
        jbGuardar = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jbLeerSalida = new javax.swing.JButton();
        jbLeerEntrada = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jcbUsuarios = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jrbCliente = new javax.swing.JRadioButton();
        jrbProveedor = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMiEditar = new javax.swing.JMenuItem();
        jMIImprimir = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bascula camionera");
        setResizable(false);

        jLabel1.setText("ID Pesada");

        jLabel2.setText("Placas");

        jLabel3.setText("Operador");

        jLabel4.setText("Entrada");

        jLabel5.setText("Peso de entrada");

        jLabel6.setText("Salida");

        jLabel7.setText("Peso de salida");

        jtfIdPesada.setToolTipText("");
        jtfIdPesada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdPesadaActionPerformed(evt);
            }
        });

        jtfPlacas.setMinimumSize(new java.awt.Dimension(6, 200));

        jtfOperador.setMinimumSize(new java.awt.Dimension(6, 200));

        jtfHoraEntrada.setMinimumSize(new java.awt.Dimension(6, 200));

        jtfPesoEntrada.setMinimumSize(new java.awt.Dimension(6, 200));

        jtfHoraSalida.setMinimumSize(new java.awt.Dimension(6, 200));

        jtfPesoSalida.setMinimumSize(new java.awt.Dimension(6, 200));

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbImprimir.setText("Iimprimir");
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registro de báscula camionera");

        jbLeerSalida.setText("Leer");
        jbLeerSalida.setName(""); // NOI18N
        jbLeerSalida.setPreferredSize(new java.awt.Dimension(45, 23));
        jbLeerSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLeerSalidaActionPerformed(evt);
            }
        });

        jbLeerEntrada.setText("Leer");
        jbLeerEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLeerEntradaActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel9.setText("Usuario");

        jcbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUsuariosActionPerformed(evt);
            }
        });

        bgTipoPesada.add(jrbCliente);
        jrbCliente.setText("Cliente");

        bgTipoPesada.add(jrbProveedor);
        jrbProveedor.setText("Proveedor");

        jMenu1.setText("Archivo");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Nuevo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Buscar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMiEditar.setText("Editar un registro");
        jMiEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiEditarActionPerformed(evt);
            }
        });
        jMenu1.add(jMiEditar);

        jMIImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMIImprimir.setText("Imprimir");
        jMIImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIImprimirActionPerformed(evt);
            }
        });
        jMenu1.add(jMIImprimir);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem6.setText("COM");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem4.setText("Acerca de");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbCliente)
                                .addGap(18, 18, 18)
                                .addComponent(jrbProveedor))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfIdPesada)
                                    .addComponent(jtfPlacas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfOperador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfHoraEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfPesoEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfHoraSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfPesoSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jcbUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jbLeerSalida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbLeerEntrada, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbNuevo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbBuscar)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrbCliente)
                        .addComponent(jrbProveedor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfIdPesada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbNuevo)
                        .addComponent(jbBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtfPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jtfHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtfPesoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbLeerEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtfHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jtfPesoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbLeerSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbImprimir)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jbLeerSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLeerSalidaActionPerformed
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date d = new Date();
//        int intentos = 0;
        jtfHoraSalida.setText(df.format(d));
        try {
            Bascula.buscarPuerto();
        } catch (Exception e) {
            System.out.println("e");
        }
        COM reader = new COM();
//        String peso = reader.getCadena().substring(7,14);
//        while (peso.length() < 10) {
//            peso = reader.getCadena().substring(7,14);
//            if (intentos >= 10) {
//                break;
//            } else {
//                intentos++;
//            }
//        }
        jtfPesoSalida.setText(reader.getCadena().substring(7, 14));
    }//GEN-LAST:event_jbLeerSalidaActionPerformed

    private void jbLeerEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLeerEntradaActionPerformed
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date d = new Date();
//        int intentos = 0;
        jtfHoraEntrada.setText(df.format(d));
        try {
            Bascula.buscarPuerto();
        } catch (Exception e) {
            System.out.println("e");
        }
        COM reader = new COM();
//        String peso = reader.getCadena().substring(7,14);
//        while (peso.length() < 10) {
//            peso = reader.getCadena().substring(7,14);
//            if (intentos >= 10) {
//                break;
//            } else {
//                intentos++;
//            }
//        }
        jtfPesoEntrada.setText(reader.getCadena().substring(7, 14));

    }//GEN-LAST:event_jbLeerEntradaActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        Pesada pesada = new Pesada();
        boolean error = false;
        char tipo;
        int id = 0;
        try {
            id = Integer.parseInt(jtfIdPesada.getText());
        } catch (Exception e) {
            new Error(this, rootPaneCheckingEnabled, "Debe agregar un nuevo ID Pesada");
            error = true;
        }
        if (error == false) {
            if (!jrbCliente.isSelected() && !jrbProveedor.isSelected()) {
                new Error(this, rootPaneCheckingEnabled, "Debe indicar si es CLIENTE o PROVEEDOR");

            } else {
                pesada.setIdUsuario(new UsuarioDAO().getIdUsuario(jcbUsuarios.getItemAt(jcbUsuarios.getSelectedIndex())));
                pesada.setiDPesada(id);
                pesada.setPlacas(jtfPlacas.getText());
                pesada.setOperador(jtfOperador.getText());
                pesada.setEntrada(jtfHoraEntrada.getText());
                pesada.setPesoEntrada(jtfPesoEntrada.getText());
                pesada.setSalida(jtfHoraSalida.getText());
                pesada.setPesoSalida(jtfPesoSalida.getText());
                if (jrbCliente.isSelected()) {
                    tipo = 'C';
                } else {
                    tipo = 'P';
                }
                if (jrbProveedor.isSelected()) {
                    tipo = 'P';
                } else {
                    tipo = 'C';
                }
                pesada.setTipoPesada(tipo);
                PesadaDAO pdao = new PesadaDAO();

                if (pdao.modificar(pesada)) {
                    jtfIdPesada.setText(null);
                    jtfPlacas.setText(null);
                    jtfOperador.setText(null);
                    jtfHoraEntrada.setText(null);
                    jtfPesoEntrada.setText(null);
                    jtfHoraSalida.setText(null);
                    jtfPesoSalida.setText(null);

                    Guardado g = new Guardado(this, rootPaneCheckingEnabled);
                } else {
                    System.out.println("problema al guardar el registro");
                }
            }
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtfIdPesadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdPesadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdPesadaActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        PesadaDAO pesadadao = new PesadaDAO();
        jtfIdPesada.setText(Integer.toString(pesadadao.nuevo()));
        jtfPlacas.setText(null);
        jtfOperador.setText(null);
        jtfHoraEntrada.setText(null);
        jtfPesoEntrada.setText(null);
        jtfHoraSalida.setText(null);
        jtfPesoSalida.setText(null);
        jbLeerEntrada.setEnabled(true);
        jbLeerSalida.setEnabled(false);
        jcbUsuarios.setEnabled(true);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        BuscaID buscaID = new BuscaID(this, rootPaneCheckingEnabled);
        buscaID.setVisible(true);
        Pesada pesada = (Pesada) buscaID.getPesada();
        Usuario u = (Usuario) new UsuarioDAO().consultar(pesada.getIdUsuario());
        jcbUsuarios.setSelectedItem(u.getUsuario());
        jtfIdPesada.setText("" + pesada.getiDPesada());
        jtfPlacas.setText(pesada.getPlacas());
        jtfOperador.setText(pesada.getOperador());
        jtfHoraEntrada.setText(pesada.getEntrada());
        jtfPesoEntrada.setText(pesada.getPesoEntrada());
        jtfHoraSalida.setText(pesada.getSalida());
        jtfPesoSalida.setText(pesada.getPesoSalida());

//        if (((pesada.getEntrada().equals("")) || (pesada.getEntrada().equals(" ")))
//                && ((pesada.getPesoEntrada().equals("")) || (pesada.getPesoEntrada().equals(" ")))
//                && ((pesada.getSalida().equals("")) || (pesada.getSalida().equals(" ")))
//                && ((pesada.getPesoSalida().equals("")) || (pesada.getPesoSalida().equals(" ")))) {
//            jbLeerEntrada.setEnabled(true);
//            jbLeerSalida.setEnabled(false);
//            jbImprimir.setEnabled(true);
//            jMIImprimir.setEnabled(true);
//        } else 
        if (!((pesada.getEntrada().equals("")) || (pesada.getEntrada().equals(" ")))
                && !((pesada.getPesoEntrada().equals("")) || (pesada.getPesoEntrada().equals(" ")))
                && ((pesada.getSalida().equals("")) || (pesada.getSalida().equals(" ")))
                && ((pesada.getPesoSalida().equals("")) || (pesada.getPesoSalida().equals(" ")))) {
            jbLeerEntrada.setEnabled(false);
            jbLeerSalida.setEnabled(true);
            jbImprimir.setEnabled(true);
            jMIImprimir.setEnabled(true);
            jcbUsuarios.setEnabled(false);
        } else if (!((pesada.getEntrada().equals("")) || (pesada.getEntrada().equals(" ")))
                && !((pesada.getPesoEntrada().equals("")) || (pesada.getPesoEntrada().equals(" ")))
                && !((pesada.getSalida().equals("")) || (pesada.getSalida().equals(" ")))
                && !((pesada.getPesoSalida().equals("")) || (pesada.getPesoSalida().equals(" ")))) {
            jbLeerEntrada.setEnabled(false);
            jbLeerSalida.setEnabled(false);
            jbImprimir.setEnabled(true);
            jMIImprimir.setEnabled(true);
            jcbUsuarios.setEnabled(false);
        } else {
            jbLeerEntrada.setEnabled(true);
            jbLeerSalida.setEnabled(false);
            jbImprimir.setEnabled(true);
            jMIImprimir.setEnabled(true);
            jcbUsuarios.setEnabled(false);
        }

//        if ((!pesada.getEntrada().equals("") && !pesada.getEntrada().equals(" "))
//                && (!pesada.getPesoEntrada().equals("") && !pesada.getPesoEntrada().equals(" "))) {
//            jbLeerEntrada.setEnabled(false);
//        } else {
//            jbLeerEntrada.setEnabled(true);
//        }
//        if ((!pesada.getSalida().equals("") && !pesada.getSalida().equals(" "))
//                && (!pesada.getPesoSalida().equals("") && !pesada.getPesoSalida().equals(" "))) {
//            jbLeerSalida.setEnabled(false);
//        } else {
//            jbLeerSalida.setEnabled(true);
//        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jbBuscarActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jbNuevoActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed
        if ((jtfIdPesada.getText().equals("") || jtfIdPesada.getText().equals(" "))
                || (jtfPlacas.getText().equals("") || jtfPlacas.getText().equals(" "))
                || (jtfOperador.getText().equals("") || jtfOperador.getText().equals(" "))
                || (jtfHoraEntrada.getText().equals("") || jtfHoraEntrada.getText().equals(" "))
                || (jtfPesoEntrada.getText().equals("") || jtfPesoEntrada.getText().equals(" "))
                || (jtfHoraSalida.getText().equals("") || jtfHoraSalida.getText().equals(" "))
                || (jtfPesoSalida.getText().equals("") || jtfPesoSalida.getText().equals(" "))) {
            new Error(this, rootPaneCheckingEnabled, "Datos incompletos");
        } else {
            Pesada pesada = new Pesada();
            pesada.setIdUsuario(new UsuarioDAO().getIdUsuario(jcbUsuarios.getItemAt(jcbUsuarios.getSelectedIndex())));
            pesada.setiDPesada(Integer.parseInt(jtfIdPesada.getText()));
            pesada.setPlacas(jtfPlacas.getText());
            pesada.setOperador(jtfOperador.getText());
            pesada.setEntrada(jtfHoraEntrada.getText());
            pesada.setPesoEntrada(jtfPesoEntrada.getText());
            pesada.setSalida(jtfHoraSalida.getText());
            pesada.setPesoSalida(jtfPesoSalida.getText());
            Imprimir i = new Imprimir(this, rootPaneCheckingEnabled, pesada);
            i.setVisible(true);
            System.out.println("Imprimiendo comprobante");
            jbGuardarActionPerformed(evt);
        }
    }//GEN-LAST:event_jbImprimirActionPerformed

    private void jMIImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIImprimirActionPerformed
        jbImprimirActionPerformed(evt);
    }//GEN-LAST:event_jMIImprimirActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new COMEstatus(this, rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMiEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiEditarActionPerformed

    }//GEN-LAST:event_jMiEditarActionPerformed

    private void jcbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUsuariosActionPerformed
//        JOptionPane.showMessageDialog(null, new UsuarioDAO().getIdUsuario(jcbUsuarios.getItemAt(jcbUsuarios.getSelectedIndex())));
    }//GEN-LAST:event_jcbUsuariosActionPerformed

    public void setJtfIdPesada(int id) {
        jtfIdPesada.setText("" + id);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void setLocationCenter() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoPesada;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMIImprimir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMiEditar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbLeerEntrada;
    private javax.swing.JButton jbLeerSalida;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JComboBox<String> jcbUsuarios;
    private javax.swing.JRadioButton jrbCliente;
    private javax.swing.JRadioButton jrbProveedor;
    private javax.swing.JTextField jtfHoraEntrada;
    private javax.swing.JTextField jtfHoraSalida;
    private javax.swing.JTextField jtfIdPesada;
    private javax.swing.JTextField jtfOperador;
    private javax.swing.JTextField jtfPesoEntrada;
    private javax.swing.JTextField jtfPesoSalida;
    private javax.swing.JTextField jtfPlacas;
    // End of variables declaration//GEN-END:variables
}
